services:
  mysql:
    image: mysql:8.0
    container_name: pos-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pos_system
    ports:
      - "3306:3306"
    volumes:
      - pos_mysql_data:/var/lib/mysql

volumes:
  pos_mysql_data:
